### ISSUE TITLE
Help with esp8266 hanging

### ISSUE THREAD

**Issue by sheminasalam** [gadjet/Window-Door-sensor-Version-5#1]
Hi there I have an issue with version 1 of this sensor. It would be good if you could help me out with it. My sensor can detect when the window is open without any issues. But when it comes to closing, it wont work all the time. I tried to diagnose the issue with serial monitor and found that when the window is being closed, the esp8266 starts to wake but before executing any functions, it hangs up. One more thing I noticed is that when this problem occurs the onboard led won't even blink like when the board boots up. But when we push the reset button(GPIO16) in closed state, the device boots fine and completes action and sleeps.

 Is this a code issue or some hardware issue? what can be the issue? I am confused because majority of the time this works fine.

**Comment by gadjet** [comment]
Hi sheminasalam,
When you say version 1 do you mean this version (version 5)or the first project.

**Comment by sheminasalam** [comment]
first project on which the youtube video was made

**Comment by gadjet** [comment]
OK, to save confusion, can you raise the issue in the first version then so if others have the same problem they can see the issue in the right place :-) thanks.

**Comment by sheminasalam** [comment]
Is the video version 1?
 I just followed link on video

**Comment by gadjet** [comment]
The video isn't mine, I was inspired by the video to create my own version based on Maker Meiks
