### ISSUE TITLE
Re-label RX and TX

### ISSUE THREAD

**Issue by thematrixincendies** [gadjet/Window-Door-sensor-Version-5#9]
Currently, the markings on the PCB read "TX" and "RX". The problem is, that the pin labeled "RX" actually connects to the ESP's "TX" pin and the pin labeled "TX" actually connects to the ESP's "RX" pin".
I guess this was done to be able to connect "TX" of a flasher to "TX" on the board and the same for the "RX" pin.
However, no board does this and it is counter intuitive.

**Comment by gadjet** [comment]
Hmm, you are right but to be honest I do it so that I can just plug my USB to Serial flasher PCB straight on to it and the labels match, afterall it's my design ;-)

**Comment by thematrixincendies** [comment]
Sure, it's your design. You might at least want to add a note to the readme, because, trust me, nobody expects this.

**Comment by thematrixincendies** [comment]
Ah, you already did, thanks!
